#site:
#  title: QASCHOLAR Docs
# url: https://qascholars.github.io/qascholar-test-documentation

site:
  title: QASCHOLAR - Test Documentation
  start_page: qascholar-docs::getting-started.adoc


content:
  sources:
    - url: ./docs/qascholar-docs
      branches: HEAD
      #start_path: modules/ROOT/nav.adoc



output:
  dir: ./build/site
