#site:
#  title: QASCHOLAR Docs
# url: https://qascholars.github.io/qascholar-test-documentation

site:
  title: QASCHOLAR - Test Documentation
  start_page: qascholar-docs::getting-started.adoc


content:
  sources:
    - url: .
      branches: main
      #start_path: modules/ROOT/nav.adoc

ui:
  bundle:
    url: ./ui/ui-bundle.zip
    snapshot: true

output:
  dir: ./build/site
