== Timeouts

When using Playwright, you can set timeouts for various operations to ensure that your tests do not hang indefinitely. 

Timeouts can be set globally for the entire page or specifically for certain actions like navigation or element interactions. Without proper timeout settings, your tests may fail or take longer than expected to complete.

Timeouts are typically set in milliseconds (eg. 30000 ms for 30 seconds). The default timeout for most Playwright operations is 30 seconds, but you can customize this based on your application's performance and requirements.

Timeouts can be configured in playwright.config.js or directly in your test scripts. The settings can be adjusted based on the expected load times of your application and the complexity of the operations being performed. The setting can be set globally or per test basis. 

Here are some common timeout settings you might want to configure:

=== Global Timeout:

PlayWright Test supports a global timeout for the whole test run. There is no default value for this setting, so you need to set it explicitly in your configuration file.

```javascript
import { defineConfig } from '@playwright/test';

export default defineConfig({
  globalTimeout: 3_600_000, // Set global timeout to 1 hour
  //globalTimeout: 3600000, // Set default timeout for each action to 30 seconds
});

```

=== Test Timeout:
You can set a timeout for individual tests using the `test.setTimeout()` method. This is useful if you have specific tests that may take longer than the default timeout.

```javascript
import { test } from '@playwright/test';

test('long-running test', async ({ page }) => {
  test.setTimeout(120_000); // Set timeout to 2 minutes
  await page.goto('https://example.com');
  // Perform test actions
});
```

=== Navigation Timeout

If you want to set a specific timeout for navigation operations, you can use the `page.goto()` method with a timeout option.

```javascript
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com', { timeout: 10000 }); // Set navigation timeout to 10 seconds
  await browser.close();
})();
```

=== Element Timeout

For element interactions, you can set a timeout using the `locator.waitFor()` method.

```javascript
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  const button = page.locator('button#submit');
  await button.waitFor({ timeout: 3000 }); // Set element timeout to 3 seconds
  await button.click();
  await browser.close();
})();
```

By configuring these timeout settings, you can ensure that your Playwright tests are more robust and less likely to hang indefinitely.